name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          APP_DB_USERNAME: postgres
          APP_DB_PASSWORD: postgres
          APP_DB_NAME: postgres
    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-postgresql/docker-compose.yaml" up -d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
